version: '3.8'
services:
  app:
    container_name: app
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      PORT: 3000
      DB_HOST: db
      DB_USER: root
      DB_PASSWORD: password
      DB_NAME: CadeauxAnniv
    command: npm start

  db:
    image: mysql:5.7
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: CadeauxAnniv
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
