version: '3.8'
services:
  app:
    container_name: app
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - db
    command: npm start

  db:
    container_name: db
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: CadeauxAnniv
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
